spring.datasource.url=jdbc:postgresql://localhost:5432/gamestore
spring.datasource.username=gamestore
spring.datasource.password=gamestore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never
